### ISSUE TITLE
Тип возвращаемый методом

### ISSUE THREAD

**Issue by AlexDaSoul** [splincodewd/client-logger#10]
https://github.com/splincodewd/client-logger/blob/d8b58a877072e1d93dcc7e92e7f652be2dc3a439/src/logger.ts#L88

Очень хорошая практика - указывать то, что должен возвращать метод. Причем это должен быть один результат, или результат одного типа по смыслу, типа 

`method(): Promise<boolean> | Observable<boolean> | boolean`

Тут явно контролируется возврат булева значения. Что-то вот такое:

`method(): boolean | string`

Считается плохим кодом. Сейчас из-за непонятного loop с мультивозвратами, как раз что-то такое и должно получиться. Теряется контроль типов

**Comment by splincode** [comment]
понял, постараюсь добавить
