### ISSUE TITLE
Нужен DI :)

### ISSUE THREAD

**Issue by AlexDaSoul** [splincodewd/client-logger#11]
https://github.com/splincodewd/client-logger/blob/d8b58a877072e1d93dcc7e92e7f652be2dc3a439/src/logger.ts#L94

**Comment by splincode** [comment]
Пока не понятно о чем речь, DI я хотел чтобы появился в Angular модуле, сейчас же я хочу обычный логгер который доступен как альтернатива инициализированному console объекту, что в этом случае?

**Comment by AlexDaSoul** [comment]
Лучше сразу начинать делать так, как это будет в релизе. Потом тебе придется переписать четверть приложения. Там свои тонкости. Нужно добавлять конфигуратор, нужно создавать новые описания интерфейсов для конфига, задавать дефолтные параметры. Лучше это сделать сразу, чем потом не доделывать, но переделывать

**Comment by splincode** [comment]
Погоди, я просто не знаю, как делается DI не в контексте Angular и имеет ли это смысл для простых проектов?
