### ISSUE TITLE
eslint, tslint

### ISSUE THREAD

**Issue by AlexDaSoul** [splincodewd/client-logger#12]
https://github.com/splincodewd/client-logger/blob/d8b58a877072e1d93dcc7e92e7f652be2dc3a439/src/logger.ts#L24

Понятно, что это стайл, но считается не очень хорошей практикой пропускать скобки в if else for и т.д. Это трудно читать и вообщен непонятно, куда программист который так пишет, расходует сэкономленное время))

**Comment by splincode** [comment]
да, я понял, я убрал эту строчку вообще

**Comment by splincode** [comment]
пока еще не добаил eslint, tslint
