### ISSUE TITLE
any - плохо

### ISSUE THREAD

**Issue by AlexDaSoul** [splincodewd/client-logger#13]
https://github.com/splincodewd/client-logger/blob/d8b58a877072e1d93dcc7e92e7f652be2dc3a439/src/logger.ts#L28

Если приходится принудительно приводить к типу, да еще это any, значит где-то что-то не так. Это можно принимать за сигнализатор

**Comment by splincode** [comment]
Проблема в том, что 

![image](https://user-images.githubusercontent.com/12021443/34080367-8ef7fa3c-e34d-11e7-8870-b952616563a6.png)

Мне нужно возвращать строку, а принимать на вход что-то определенного типа Number

**Comment by AlexDaSoul** [comment]
Ну ведь не зря же он пишет предупреждения. Не нужно с ними бороться. Когда ты их побеждаешь, то, как правило, создаешь самые глупые косяки. Акцессоры не могут возвращать иной тип от параметра, это нарушает типовую безопасность. Если тебе требуется во что бы то ни стало менять тип, то не используй акцессор, ищи другое решение

**Comment by splincode** [comment]
Хорошо, тогда сделаю другие методы, но публичные, или можно поступить проще, возвращать единый тип)
