### ISSUE TITLE
Тут можно сделать настраиваемое форматирование

### ISSUE THREAD

**Issue by AlexDaSoul** [splincodewd/client-logger#20]
https://github.com/splincodewd/client-logger/blob/509ee637f2a88d69cb3d4ab73ae52abe07d5efe9/src/json-parse.class.ts#L7

Типа таб или пробел или 2 пробела, 4 и т.п.

**Comment by splincode** [comment]
```ts
logger.printJSON(json, {
  enableColor: true,
  space: '\t' || '\s\s' || 2  .. etc,
  style: {
   _string: 'color: red',
   _number: 'color: yellow',
   _boolean: 'color: blue',
  _null:  'color: magenta',
  _key: 'color: red'
  }
}); 
```

**Comment by splincode** [comment]
https://github.com/splincodewd/client-logger/commit/b7e95abe323d9f01460c4fd166783189bf6422b6
