### ISSUE TITLE
Такое принято писать в d.ts для объекта Window

### ISSUE THREAD

**Issue by AlexDaSoul** [splincodewd/client-logger#26]
https://github.com/splincodewd/client-logger/blob/509ee637f2a88d69cb3d4ab73ae52abe07d5efe9/src/clipboard.class.ts#L11

**Comment by splincode** [comment]
@AlexDaSoul а как принято?

**Comment by AlexDaSoul** [comment]
https://stackoverflow.com/questions/12709074/how-do-you-explicitly-set-a-new-property-on-window-in-typescript?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa
