### ISSUE TITLE
Дублируется инициализация переменных

### ISSUE THREAD

**Issue by AlexDaSoul** [splincodewd/client-logger#6]
https://github.com/splincodewd/client-logger/blob/d8b58a877072e1d93dcc7e92e7f652be2dc3a439/src/logger.ts#L22

Один раз при объявлении

`private colorLabel: LoggerColor = DEFAULT_COLORS;
private configLabel: LoggerLabels = DEFAULT_LABELS;`

Второй раз в конструкторе. Потенциально может осложнить дебаг, нужно будет дополнительно уточнять проблему. Ну и в целом считается хорошей практикой инициализировать поля единожды, чтобы отделить по смыслу инициализацию от измиенения значений. Тем более тут конфиг, его вообще в объявлении можно пометить как readonly для лучшей читаемости

**Comment by splincode** [comment]
но мне ведь нужно его переопределять, что значит как readonly пометить?

**Comment by AlexDaSoul** [comment]
Речь о том, что ты присваиваешь значения и тут же переписываешь их в конструкторе. Лишняя операция, которая потенциально может запутать код
