### ISSUE TITLE
Инициализация литералом объекта

### ISSUE THREAD

**Issue by AlexDaSoul** [splincodewd/client-logger#7]
https://github.com/splincodewd/client-logger/blob/d8b58a877072e1d93dcc7e92e7f652be2dc3a439/src/logger.ts#L19

Не очень хорошее дело. Если параметр может быть пустым, то правильнее сделать его необязательным (options?:). Если нужно непременно проинициализировать его пустым, то нужно указывать не пустой литерал объекта, а полный список его полей, согласно указанного интерфейса внутри литерала

`constructor(options: LoggerConfig = { showLevel: ... }) {`

**Comment by splincode** [comment]
Почему нельзя так? Ведь дефолтный конфиг инициализируется раньше

private colorLabel: LoggerColors = DEFAULT_COLORS;
    private configLabel: LoggerLabels = DEFAULT_LABELS;

```
constructor(options: Partial<LoggerConfig> = {}) { 
```

**Comment by AlexDaSoul** [comment]
Просто сделай конфиг через DI, тогда будет понятно почему
