### ISSUE TITLE
Не очень понятен смысл этого выражения

### ISSUE THREAD

**Issue by AlexDaSoul** [splincodewd/client-logger#8]
https://github.com/splincodewd/client-logger/blob/d8b58a877072e1d93dcc7e92e7f652be2dc3a439/src/logger.ts#L15

Это что-то типа заглушки, которая возвращает пустое лямбда-выражение? Если нужно принудительно возвращать ничто, значит что-то не до конца продумано

**Comment by splincode** [comment]
noop - в программирования часто можно встретить сокращенное название переменной "no operations"

Если я меняю уровень логгирования, тогда я отключаю ту или иную функцию, значит возвращаю ничто, это ведь вполне адекватное поведение для логгера, разве нет?

**Comment by AlexDaSoul** [comment]
Возвращай null - это и есть то самое "ничто", котрое допустимо в строго-типизированном коде в качестве альтернативы значению. Его даже не обязательно возвращать явно, достаточно просто ничего не возвращать по условию. Это будет равнозначно return null
